# Read the documentation: https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/Resources/doc/setup.md
fos_elastica:
    clients:
        default:
            url: '%env(ELASTICSEARCH_URL)%'
    serializer:
        serializer: jms_serializer
    indexes:
        user:
            finder: ~
            index_name: user_%kernel.environment%
            types:
                user:
                    persistence:
                        model: Bkstg\FOSUserBundle\Entity\User
        production:
            finder: ~
            index_name: production_%kernel.environment%
            types:
                production:
                    persistence:
                        model: Bkstg\CoreBundle\Entity\Production
        post:
            finder: ~
            index_name: post_%kernel.environment%
            types:
                post:
                    persistence:
                        model: Bkstg\NoticeBoardBundle\Entity\Post
        resource:
            finder: ~
            index_name: resource_%kernel.environment%
            types:
                resource:
                    persistence:
                        model: Bkstg\ResourceBundle\Entity\Resource
        schedule:
            finder: ~
            index_name: schedule_%kernel.environment%
            types:
                schedule:
                    persistence:
                        model: Bkstg\ScheduleBundle\Entity\Schedule
        event:
            finder: ~
            index_name: event_%kernel.environment%
            types:
                event:
                    persistence:
                        model: Bkstg\ScheduleBundle\Entity\Event
