fos_user:
  db_driver: orm
  firewall_name: main
  user_class: Bkstg\FOSUserBundle\Entity\User
  service:
      mailer: fos_user.mailer.twig_swift
  from_email:
    address: noreply@example.com
    sender_name: noreply
