sonata_media:
    default_context: default
    db_driver: doctrine_orm
    class:
        media: Bkstg\MediaBundle\Entity\Media
        gallery: Bkstg\MediaBundle\Entity\Gallery
        gallery_has_media: Bkstg\MediaBundle\Entity\GalleryHasMedia
    providers:
        image:
            resizer: sonata.media.resizer.simple
    contexts:
        default:
            providers:
                - sonata.media.provider.image
                - sonata.media.provider.file
            formats:
                square: { width: 256, height: 256, quality: 90 }
                small: { width: 256 , quality: 90 }
                big: { width: 512 , quality: 90 }
                card_banner: { width: 705, height: 370, quality: 90 }
                full_banner: { width: 5120, quality: 90 }
    cdn:
        server:
            path: /media/serve
    filesystem:
        local:
            directory: "%kernel.root_dir%/../var/uploads/media"
            create: true
