twig:
    globals:
        google_api_key: '%env(GOOGLE_API_KEY)%'
        full_date: 'F j, Y g:i a'
        full_date_weekday: 'l, F j, Y g:i a'
    paths: ['%kernel.project_dir%/templates']
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
        - 'bootstrap_4_layout.html.twig'
        - '@SonataMedia/Form/media_widgets.html.twig'
        - '_form_collection.html.twig'
        - '_units_widgets.html.twig'
