twig:
    globals:
        google_api_key: '%env(GOOGLE_API_KEY)%'
        full_date: 'M d, Y g:i:s a'
    paths: ['%kernel.project_dir%/templates']
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
        - 'bootstrap_4_layout.html.twig'
        - '_form_collection.html.twig'
