version: '3'

services:
  db:
    image: mariadb:10
    environment:
      MYSQL_DATABASE: app
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker/data/mariadb:/docker-entrypoint-initdb.d
volumes:
  dbdata:
