bkstg_user:
    resource: '@BkstgFOSUserBundle/Resources/config/routing/all.yml'
bkstg_media:
    resource: '@BkstgMediaBundle/Resources/config/routing/all.yml'
bkstg_core:
    resource: '@BkstgCoreBundle/Resources/config/routing/all.yml'
