bkstg_user:
    resource: '@BkstgFOSUserBundle/Resources/config/routing/all.yml'
bkstg_media:
    prefix: /media
    resource: '@BkstgMediaBundle/Resources/config/routing/all.yml'
bkstg_notice_board:
    resource: '@BkstgNoticeBoardBundle/Resources/config/routing/all.yml'
    prefix: /{production_slug}/board
bkstg_schedule:
    resource: "@BkstgScheduleBundle/Resources/config/routing/all.yml"
    prefix:   /{production_slug}/schedule
bkstg_core:
    resource: '@BkstgCoreBundle/Resources/config/routing/all.yml'
