bkstg_notification:
    resource: "@BkstgNotificationBundle/Resources/config/routing/all.yml"
    prefix:   /notification
bkstg_notice_board:
    resource: "@BkstgNoticeBoardBundle/Resources/config/routing/all.yml"
    prefix:   /{production_slug}/board
bkstg_media:
    resource: "@BkstgMediaBundle/Resources/config/routing/all.yml"
    prefix: /media
bkstg_fos_user:
    resource: "@BkstgFOSUserBundle/Resources/config/routing/all.yml"
    prefix:   /
bktsg_core:
    resource: '@BkstgCoreBundle/Resources/config/routing/all.yml'
_monitor:
    resource: "@LiipMonitorBundle/Resources/config/routing.xml"
    prefix: /admin/monitor/health
