media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /media
bkstg_fos_user:
    resource: "@BkstgFOSUserBundle/Resources/config/routing/all.yml"
    prefix:   /
bktsg_core:
    resource: '@BkstgCoreBundle/Resources/config/routing/all.yml'
