bkstg_search:
    resource: "@BkstgSearchBundle/Resources/config/routing.yml"
    prefix:   /search
bkstg_notification:
    resource: "@BkstgTimelineBundle/Resources/config/routing/all.yml"
    prefix:   /timeline
bkstg_notice_board:
    resource: "@BkstgNoticeBoardBundle/Resources/config/routing/all.yml"
    prefix:   /{production_slug}/board
bkstg_schedule:
    resource: "@BkstgScheduleBundle/Resources/config/routing/all.yml"
    prefix:   /{production_slug}/schedule
bkstg_media:
    resource: "@BkstgMediaBundle/Resources/config/routing/all.yml"
    prefix: /media
bkstg_fos_user:
    resource: "@BkstgFOSUserBundle/Resources/config/routing/all.yml"
    prefix:   /
bktsg_core:
    resource: '@BkstgCoreBundle/Resources/config/routing/all.yml'
_monitor:
    resource: "@LiipMonitorBundle/Resources/config/routing.xml"
    prefix: /admin/monitor/health
