monolog:
    handlers:
        main:
            type: syslog
            action_level: error
        console:
            type:   console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
