# Contrib routes.
fos_user_security:
  resource: "@FOSUserBundle/Resources/config/routing/security.xml"
fos_user_resetting:
  resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
  prefix: /resetting
fos_user_change_password:
  resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
  prefix: /profile

# Bkstg routes.
bkstg_user:
  resource: '@BkstgFOSUserBundle/Resources/config/routing/all.yml'
bkstg_media:
  prefix: /media
  resource: '@BkstgMediaBundle/Resources/config/routing/all.yml'
bkstg_notice_board:
  resource: '@BkstgNoticeBoardBundle/Resources/config/routing/all.yml'
  prefix: /{production_slug}/board
bkstg_schedule:
  resource: '@BkstgScheduleBundle/Resources/config/routing/all.yml'
bkstg_resource:
  resource: '@BkstgResourceBundle/Resources/config/routing/all.yml'
  prefix:   /{production_slug}/resource
bkstg_core:
  resource: '@BkstgCoreBundle/Resources/config/routing/all.yml'
